minifier update
Kingdom-of-The-Moon/FiguraRewriteRewrite pull request #76
Opened 2023-04-11 08:58 UTC by lenrik1589

- Fixes Avatar loading failing silently if error being thrown is not an `Exception`
- Fixes Long strings in the script crashing the script minifier making avatar not load
- Adds new minifier mode: Abstract Syntaxt Tree minifier (i have no better name for it)

Needs more testing but doesn't crash with the avatars I have.
Contains a temporary mixin into LuaJ AST that fixes handling of non-ascii characters in short strings (needs testing with `[[]]` strings)

2023-04-11 09:12 UTC, Francy-chan requested changes

2023-04-11 09:12 UTC, Francy-chan commented on src/main/java/org/moon/figura/mixin/StrMixin.java
since we "own" the lib, those changes should be directly patched in the lib instead of mixin into it

2023-04-11 09:12 UTC, Francy-chan commented on src/main/java/org/moon/figura/parsers/LuaScriptBuilderVisitor.java
this class seems to be worthwhile to be part of the library as well

2023-04-11 09:12 UTC, Francy-chan commented on src/main/resources/figura.mixins.json
no mixin into "owned" libraries

2023-05-22 19:29 UTC, lenrik1589 commented on src/main/java/org/moon/figura/mixin/StrMixin.java
Will be resolved by Kingdom-of-The-Moon/luaj#1

2023-05-22 19:32 UTC, lenrik1589 commented on src/main/java/org/moon/figura/parsers/LuaScriptBuilderVisitor.java
This will have to be here until LuaJ has proper support for concrete syntax trees (parse trees)

2023-05-30 13:31 UTC, Francy-chan approved these changes

2023-05-30 13:31 UTC, merged